import { gf2VecMatMul, hammingWeight } from './gf2';

export interface CodeValidationResult {
  isValid: boolean;
  dMin: number;
  maxCorrectableErrors: number;
  maxDetectableErrors: number;
  distinctNonZeroColumns: boolean;
  warnings: string[];
}

/**
 * Computes minimum distance d_min and validates the linear block code generated by G and H.
 */
export function validateCode(k: number, n: number, G: number[][], H: number[][]): CodeValidationResult {
  const warnings: string[] = [];

  // Check columns of H: for single error correction (d_min >= 3), all columns of H must be non-zero and distinct
  const numCheckRows = H.length;
  const colStrings = new Set<string>();
  let hasZeroCol = false;
  let hasDuplicateCols = false;

  for (let c = 0; c < n; c++) {
    const colVec = H.map(row => row[c]);
    const colStr = colVec.join('');
    if (colVec.every(v => v === 0)) {
      hasZeroCol = true;
    }
    if (colStrings.has(colStr)) {
      hasDuplicateCols = true;
    }
    colStrings.add(colStr);
  }

  const distinctNonZeroColumns = !hasZeroCol && !hasDuplicateCols;
  if (hasZeroCol) {
    warnings.push('Parity check matrix H contains an all-zero column.');
  }
  if (hasDuplicateCols) {
    warnings.push('Parity check matrix H contains duplicate columns (single-bit errors cannot be uniquely resolved).');
  }

  // Calculate d_min: minimum Hamming weight of all non-zero codewords c = m * G
  let dMin = n;
  const maxSearchK = 11; // 2^11 = 2048 codewords, fast to evaluate

  if (k <= maxSearchK) {
    const totalCombinations = 1 << k;
    for (let i = 1; i < totalCombinations; i++) {
      const m = new Array(k);
      for (let bit = 0; bit < k; bit++) {
        m[bit] = (i >> (k - 1 - bit)) & 1;
      }
      const c = gf2VecMatMul(m, G);
      const weight = hammingWeight(c);
      if (weight > 0 && weight < dMin) {
        dMin = weight;
      }
    }
  } else {
    // For large k, approximate based on column properties or row weights of G
    dMin = Math.min(...G.map(row => hammingWeight(row)));
  }

  // Error correction capabilities:
  // t = floor((d_min - 1) / 2)
  // detection = d_min - 1
  const maxCorrectableErrors = Math.floor((dMin - 1) / 2);
  const maxDetectableErrors = dMin - 1;

  return {
    isValid: distinctNonZeroColumns && dMin >= 3,
    dMin,
    maxCorrectableErrors,
    maxDetectableErrors,
    distinctNonZeroColumns,
    warnings,
  };
}
